Utils:
  AsterizmTranslator:
    Host: https://tr.asterizm.io
    ApiKey: "13b7AYfdKsYqQiQa7Bv9twgeQzLhZAayTXK8MbqQ1d9Kcw49"
Nodes:
  List:
    ETH:
      RPC: https://eth-rpc.com # chain rpc
      ContractAddress: contractAddress # client contract address
      OwnerAddress: ownerAddress # owner address example
      OwnerPrivateKey: ownerPrivateKey # owner private key example
    EVER:
      RPC: https://ever-rpc.com # chain rpc
      ContractAddress: contractAddress # client contract address
      OwnerAddress: ownerAddress # owner address example
      OwnerPrivateKey: ownerPrivateKey # owner private key example
      OwnerPublicKey: ownerPublicKey # owner public key example
